// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/types.proto

package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TokenMeta struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Decimals             int32    `protobuf:"varint,3,opt,name=Decimals,proto3" json:"Decimals,omitempty"`
	InitialSupply        int64    `protobuf:"varint,4,opt,name=InitialSupply,proto3" json:"InitialSupply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMeta) Reset()         { *m = TokenMeta{} }
func (m *TokenMeta) String() string { return proto.CompactTextString(m) }
func (*TokenMeta) ProtoMessage()    {}
func (*TokenMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_0a8d55251d4972dc, []int{0}
}
func (m *TokenMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMeta.Unmarshal(m, b)
}
func (m *TokenMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMeta.Marshal(b, m, deterministic)
}
func (dst *TokenMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMeta.Merge(dst, src)
}
func (m *TokenMeta) XXX_Size() int {
	return xxx_messageInfo_TokenMeta.Size(m)
}
func (m *TokenMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMeta proto.InternalMessageInfo

func (m *TokenMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TokenMeta) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenMeta) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *TokenMeta) GetInitialSupply() int64 {
	if m != nil {
		return m.InitialSupply
	}
	return 0
}

type MapEntry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapEntry) Reset()         { *m = MapEntry{} }
func (m *MapEntry) String() string { return proto.CompactTextString(m) }
func (*MapEntry) ProtoMessage()    {}
func (*MapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_0a8d55251d4972dc, []int{1}
}
func (m *MapEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapEntry.Unmarshal(m, b)
}
func (m *MapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapEntry.Marshal(b, m, deterministic)
}
func (dst *MapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapEntry.Merge(dst, src)
}
func (m *MapEntry) XXX_Size() int {
	return xxx_messageInfo_MapEntry.Size(m)
}
func (m *MapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MapEntry proto.InternalMessageInfo

func (m *MapEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MapEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenMeta)(nil), "TokenMeta")
	proto.RegisterType((*MapEntry)(nil), "MapEntry")
}

func init() { proto.RegisterFile("types/types.proto", fileDescriptor_types_0a8d55251d4972dc) }

var fileDescriptor_types_0a8d55251d4972dc = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0x95, 0x5c, 0x9c, 0x21, 0xf9,
	0xd9, 0xa9, 0x79, 0xbe, 0xa9, 0x25, 0x89, 0x42, 0x42, 0x5c, 0x2c, 0x7e, 0x89, 0xb9, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x70, 0x65, 0x6e, 0x52,
	0x7e, 0x8e, 0x04, 0x13, 0x58, 0x14, 0xca, 0x13, 0x92, 0xe2, 0xe2, 0x70, 0x49, 0x4d, 0xce, 0xcc,
	0x4d, 0xcc, 0x29, 0x96, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf3, 0x85, 0x54, 0xb8, 0x78,
	0x3d, 0xf3, 0x32, 0x4b, 0x32, 0x13, 0x73, 0x82, 0x4b, 0x0b, 0x0a, 0x72, 0x2a, 0x25, 0x58, 0x14,
	0x18, 0x35, 0x98, 0x83, 0x50, 0x05, 0x95, 0x8c, 0xb8, 0x38, 0x7c, 0x13, 0x0b, 0x5c, 0xf3, 0x4a,
	0x8a, 0x2a, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xa1, 0x16, 0x83, 0x98, 0x42, 0x22, 0x5c,
	0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x50, 0x6b, 0x21, 0x9c, 0x24, 0x36, 0xb0, 0xab, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x3f, 0xd1, 0xf7, 0xca, 0x00, 0x00, 0x00,
}
